# Generated by Django 6.1.1 on 2026-09-23 17:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0011_asistencia_metodo_app'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PagoStripe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('moneda', models.CharField(default='MXN', max_length=3)),
                ('estatus', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PROCESANDO', 'Procesando'), ('PAGADO', 'Pagado'), ('FALLIDO', 'Fallido'), ('CANCELADO', 'Cancelado'), ('REEMBOLSADO', 'Reembolsado')], default='PENDIENTE', max_length=20)),
                ('referencia', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('stripe_checkout_session_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('checkout_url', models.URLField(blank=True, max_length=1000)),
                ('pagado_en', models.DateTimeField(blank=True, null=True)),
                ('detalle_error', models.TextField(blank=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos_stripe', to='core.alumno')),
                ('membresia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos_stripe', to='core.membresia')),
                ('pago', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stripe', to='core.pago')),
                ('solicitado_por', models.ForeignKey(blank=True, help_text='Cuenta que generó la liga de pago (el alumno o un administrativo).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_stripe_solicitados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pago en línea',
                'verbose_name_plural': 'Pagos en línea',
                'ordering': ['-creado_en', '-id'],
            },
        ),
        migrations.CreateModel(
            name='EventoStripe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=255, unique=True)),
                ('tipo', models.CharField(max_length=255)),
                ('procesado_en', models.DateTimeField(auto_now_add=True)),
                ('pago_stripe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos', to='payments.pagostripe')),
            ],
            options={
                'verbose_name': 'Evento de Stripe',
                'verbose_name_plural': 'Eventos de Stripe',
                'ordering': ['-procesado_en', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='pagostripe',
            index=models.Index(fields=['estatus'], name='payments_pa_estatus_b906f6_idx'),
        ),
        migrations.AddIndex(
            model_name='pagostripe',
            index=models.Index(fields=['actualizado_en'], name='payments_pa_actuali_55bc4a_idx'),
        ),
    ]
