# Generated by Django 6.1.1 on 2026-09-04 17:39

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('nombres', models.CharField(max_length=120)),
                ('apellidos', models.CharField(max_length=120)),
                ('apodo', models.CharField(blank=True, help_text='Nombre de peleador, tipo Tapology', max_length=60)),
                ('edad', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('peso_actual', models.DecimalField(blank=True, decimal_places=2, help_text='En kilogramos', max_digits=5, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='alumnos/fotos/')),
                ('codigo_qr', models.CharField(blank=True, editable=False, max_length=64, unique=True)),
                ('qr_imagen', models.ImageField(blank=True, editable=False, null=True, upload_to='alumnos/qr/')),
                ('fecha_registro', models.DateField(default=django.utils.timezone.localdate)),
                ('activo', models.BooleanField(default=True)),
                ('puntos', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Alumno',
                'verbose_name_plural': 'Alumnos',
                'ordering': ['apellidos', 'nombres'],
            },
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=80, unique=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Disciplina',
                'verbose_name_plural': 'Disciplinas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Insignia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('icono', models.ImageField(blank=True, null=True, upload_to='insignias/')),
                ('criterio', models.JSONField(blank=True, default=dict, help_text='Ej. {"tipo": "racha", "valor": 10}')),
                ('puntos_bonus', models.PositiveIntegerField(default=0)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Insignia',
                'verbose_name_plural': 'Insignias',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Maestro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=120)),
                ('edad', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='maestros/fotos/')),
                ('codigo_qr', models.CharField(blank=True, editable=False, max_length=64, unique=True)),
                ('qr_imagen', models.ImageField(blank=True, editable=False, null=True, upload_to='maestros/qr/')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Maestro',
                'verbose_name_plural': 'Maestros',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Membresia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=60, unique=True)),
                ('duracion_dias', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Membresía',
                'verbose_name_plural': 'Membresías',
                'ordering': ['duracion_dias'],
            },
        ),
        migrations.CreateModel(
            name='AlumnoDisciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(default=django.utils.timezone.localdate)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='core.alumno')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='core.disciplina')),
            ],
            options={
                'verbose_name': 'Disciplina del alumno',
                'verbose_name_plural': 'Disciplinas del alumno',
            },
        ),
        migrations.AddField(
            model_name='alumno',
            name='disciplinas',
            field=models.ManyToManyField(related_name='alumnos', through='core.AlumnoDisciplina', to='core.disciplina'),
        ),
        migrations.CreateModel(
            name='Experiencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('striking', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('lucha', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('defensa', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('bjj_cinturon', models.CharField(choices=[('BLANCO', 'Blanco'), ('AZUL', 'Azul'), ('PURPURA', 'Púrpura'), ('MARRON', 'Marrón'), ('NEGRO', 'Negro')], default='BLANCO', max_length=20)),
                ('numero_torneos', models.PositiveIntegerField(default=0)),
                ('numero_sparrings', models.PositiveIntegerField(default=0)),
                ('peleas_ganadas', models.PositiveIntegerField(default=0)),
                ('peleas_perdidas', models.PositiveIntegerField(default=0)),
                ('peleas_empatadas', models.PositiveIntegerField(default=0)),
                ('metodo_victoria_favorito', models.CharField(blank=True, choices=[('KO', 'KO/TKO'), ('SUMISION', 'Sumisión'), ('DECISION', 'Decisión')], max_length=20)),
                ('peso_competencia', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('lesion_activa', models.BooleanField(default=False)),
                ('detalle_lesion', models.TextField(blank=True)),
                ('fecha_ultima_evaluacion', models.DateField(blank=True, null=True)),
                ('notas_maestro', models.TextField(blank=True)),
                ('racha_asistencia', models.PositiveIntegerField(default=0)),
                ('racha_maxima', models.PositiveIntegerField(default=0)),
                ('alumno', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='experiencia', to='core.alumno')),
            ],
            options={
                'verbose_name': 'Experiencia',
                'verbose_name_plural': 'Experiencias',
            },
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('turno', models.CharField(choices=[('MATUTINO', 'Matutino'), ('VESPERTINO', 'Vespertino'), ('NOCTURNO', 'Nocturno'), ('MIXTO', 'Mixto')], default='MATUTINO', max_length=20)),
                ('dias', models.JSONField(default=list, help_text='Lista de días, ej. ["lunes", "miercoles", "viernes"]')),
            ],
            options={
                'verbose_name': 'Horario',
                'verbose_name_plural': 'Horarios',
                'ordering': ['hora_inicio'],
                'constraints': [models.UniqueConstraint(fields=('hora_inicio', 'hora_fin', 'turno'), name='horario_unico')],
            },
        ),
        migrations.AddField(
            model_name='alumno',
            name='horario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alumnos', to='core.horario'),
        ),
        migrations.CreateModel(
            name='AlumnoInsignia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_obtencion', models.DateField(default=django.utils.timezone.localdate)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insignias_ganadas', to='core.alumno')),
                ('insignia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otorgamientos', to='core.insignia')),
            ],
            options={
                'verbose_name': 'Insignia del alumno',
                'verbose_name_plural': 'Insignias del alumno',
                'ordering': ['-fecha_obtencion'],
            },
        ),
        migrations.AddField(
            model_name='alumno',
            name='insignias',
            field=models.ManyToManyField(related_name='alumnos', through='core.AlumnoInsignia', to='core.insignia'),
        ),
        migrations.CreateModel(
            name='Grado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('nombre_grado', models.CharField(help_text='Ej. "Cinta Azul", "Grado 2"', max_length=80)),
                ('fecha_obtencion', models.DateField(default=django.utils.timezone.localdate)),
                ('notas', models.TextField(blank=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grados', to='core.alumno')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grados', to='core.disciplina')),
                ('otorgado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grados_otorgados', to='core.maestro')),
            ],
            options={
                'verbose_name': 'Grado',
                'verbose_name_plural': 'Grados',
                'ordering': ['-fecha_obtencion'],
            },
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.localdate)),
                ('hora_registro', models.DateTimeField(default=django.utils.timezone.now)),
                ('metodo_registro', models.CharField(choices=[('QR', 'Código QR'), ('MANUAL', 'Manual (maestro)')], default='QR', max_length=10)),
                ('puntos_otorgados', models.PositiveIntegerField(default=10)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='core.alumno')),
                ('disciplina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asistencias', to='core.disciplina')),
                ('horario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asistencias', to='core.horario')),
                ('registrada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asistencias_registradas', to='core.maestro')),
            ],
            options={
                'verbose_name': 'Asistencia',
                'verbose_name_plural': 'Asistencias',
                'ordering': ['-fecha', '-hora_registro'],
            },
        ),
        migrations.CreateModel(
            name='MaestroDisciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(default=django.utils.timezone.localdate)),
                ('es_titular', models.BooleanField(default=False)),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='core.disciplina')),
                ('maestro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='core.maestro')),
            ],
            options={
                'verbose_name': 'Disciplina del maestro',
                'verbose_name_plural': 'Disciplinas del maestro',
            },
        ),
        migrations.AddField(
            model_name='maestro',
            name='disciplinas',
            field=models.ManyToManyField(related_name='maestros', through='core.MaestroDisciplina', to='core.disciplina'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='membresia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alumnos', to='core.membresia'),
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PAGO_POR_VENCER', 'Pago próximo a vencer'), ('PAGO_VENCIDO', 'Pago vencido'), ('RECORDATORIO_CLASE', 'Recordatorio de clase'), ('INSIGNIA', 'Insignia obtenida'), ('GRADO', 'Nuevo grado')], max_length=30)),
                ('mensaje', models.TextField()),
                ('fecha_envio', models.DateTimeField(default=django.utils.timezone.now)),
                ('leida', models.BooleanField(default=False)),
                ('canal', models.CharField(choices=[('EMAIL', 'Email'), ('PUSH', 'Push'), ('SMS', 'SMS')], default='PUSH', max_length=10)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='core.alumno')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-fecha_envio'],
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodo', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TARJETA', 'Tarjeta'), ('TRANSFERENCIA', 'Transferencia')], default='EFECTIVO', max_length=20)),
                ('fecha_pago', models.DateField(default=django.utils.timezone.localdate)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('duracion', models.PositiveIntegerField(blank=True, help_text='Días cubiertos', null=True)),
                ('estatus', models.CharField(choices=[('PAGADO', 'Pagado'), ('VENCIDO', 'Vencido'), ('PENDIENTE', 'Pendiente')], default='PAGADO', max_length=20)),
                ('nota', models.TextField(blank=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='core.alumno')),
                ('membresia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos', to='core.membresia')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['-fecha_pago', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Torneo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('nombre_torneo', models.CharField(max_length=150)),
                ('fecha', models.DateField()),
                ('resultado', models.CharField(choices=[('GANO', 'Ganó'), ('PERDIO', 'Perdió'), ('EMPATO', 'Empató')], max_length=10)),
                ('metodo', models.CharField(blank=True, choices=[('KO', 'KO/TKO'), ('SUMISION', 'Sumisión'), ('DECISION', 'Decisión'), ('DESCALIFICACION', 'Descalificación')], max_length=20)),
                ('notas', models.TextField(blank=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='torneos', to='core.alumno')),
                ('disciplina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='torneos', to='core.disciplina')),
            ],
            options={
                'verbose_name': 'Torneo',
                'verbose_name_plural': 'Torneos',
                'ordering': ['-fecha'],
            },
        ),
        migrations.AddConstraint(
            model_name='alumnodisciplina',
            constraint=models.UniqueConstraint(fields=('alumno', 'disciplina'), name='alumno_disciplina_unica'),
        ),
        migrations.AddConstraint(
            model_name='alumnoinsignia',
            constraint=models.UniqueConstraint(fields=('alumno', 'insignia'), name='alumno_insignia_unica'),
        ),
        migrations.AddIndex(
            model_name='asistencia',
            index=models.Index(fields=['fecha'], name='core_asiste_fecha_8684f2_idx'),
        ),
        migrations.AddIndex(
            model_name='asistencia',
            index=models.Index(fields=['alumno', 'fecha'], name='core_asiste_alumno__564fc5_idx'),
        ),
        migrations.AddConstraint(
            model_name='asistencia',
            constraint=models.UniqueConstraint(fields=('alumno', 'fecha', 'disciplina', 'horario'), name='asistencia_unica_por_clase'),
        ),
        migrations.AddConstraint(
            model_name='maestrodisciplina',
            constraint=models.UniqueConstraint(fields=('maestro', 'disciplina'), name='maestro_disciplina_unica'),
        ),
        migrations.AddIndex(
            model_name='alumno',
            index=models.Index(fields=['activo'], name='core_alumno_activo_1d4afa_idx'),
        ),
        migrations.AddIndex(
            model_name='alumno',
            index=models.Index(fields=['codigo_qr'], name='core_alumno_codigo__923f9d_idx'),
        ),
        migrations.AddIndex(
            model_name='notificacion',
            index=models.Index(fields=['alumno', 'leida'], name='core_notifi_alumno__b9f80c_idx'),
        ),
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['fecha_vencimiento', 'estatus'], name='core_pago_fecha_v_98193b_idx'),
        ),
    ]
