# Generated by Django 6.1.1 on 2026-09-04 18:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='usuario',
            field=models.OneToOneField(blank=True, help_text='Cuenta con la que el alumno entra a la app.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alumno', to=settings.AUTH_USER_MODEL),
        ),
    ]
