# Generated by Django 6.1.1 on 2026-09-07 17:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alumno_usuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='enviado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='error_correo',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='estado_correo',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ENVIADO', 'Enviado'), ('FALLIDO', 'Fallido')], default='PENDIENTE', max_length=10),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='referencia_vencimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='titulo',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='pago',
            name='comprobante_enviado_en',
            field=models.DateTimeField(blank=True, help_text='Cuándo se mandó el correo con el comprobante.', null=True),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('PAGO_POR_VENCER', 'Pago próximo a vencer'), ('PAGO_VENCIDO', 'Pago vencido'), ('RECORDATORIO_CLASE', 'Recordatorio de clase'), ('INSIGNIA', 'Insignia obtenida'), ('GRADO', 'Nuevo grado'), ('MANUAL', 'Aviso administrativo')], max_length=30),
        ),
        migrations.CreateModel(
            name='Aviso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(max_length=150)),
                ('mensaje', models.TextField()),
                ('tipo_destinatario', models.CharField(choices=[('INDIVIDUAL', 'Alumno individual'), ('GRUPO', 'Grupo (horario)'), ('TODOS', 'Todos los alumnos activos')], max_length=12)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PROCESANDO', 'Procesando'), ('ENVIADA', 'Enviada'), ('FALLIDA', 'Fallida'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=12)),
                ('total_destinatarios', models.PositiveIntegerField(default=0)),
                ('total_enviadas', models.PositiveIntegerField(default=0)),
                ('total_fallidas', models.PositiveIntegerField(default=0)),
                ('procesado_en', models.DateTimeField(blank=True, null=True)),
                ('alumno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avisos', to='core.alumno')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avisos_creados', to=settings.AUTH_USER_MODEL)),
                ('horario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avisos', to='core.horario')),
            ],
            options={
                'verbose_name': 'Aviso',
                'verbose_name_plural': 'Avisos',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.AddField(
            model_name='notificacion',
            name='aviso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='core.aviso'),
        ),
        migrations.AddIndex(
            model_name='notificacion',
            index=models.Index(fields=['alumno', 'tipo', 'referencia_vencimiento'], name='core_notifi_alumno__773e92_idx'),
        ),
        migrations.AddIndex(
            model_name='aviso',
            index=models.Index(fields=['estado'], name='core_aviso_estado_43c7c4_idx'),
        ),
    ]
