# Generated by Django 6.1.1 on 2026-09-07 21:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_notificacion_enviado_en_notificacion_error_correo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='maestro',
            name='usuario',
            field=models.OneToOneField(blank=True, help_text='Cuenta con la que el maestro entra a la app.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maestro', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(max_length=150)),
                ('tipo', models.CharField(choices=[('TORNEO', 'Torneo'), ('SEMINARIO', 'Seminario'), ('EXAMEN', 'Examen de grado'), ('OTRO', 'Otro')], default='OTRO', max_length=12)),
                ('fecha', models.DateField()),
                ('lugar', models.CharField(blank=True, max_length=150)),
                ('descripcion', models.TextField(blank=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_creados', to=settings.AUTH_USER_MODEL)),
                ('disciplina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos', to='core.disciplina')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['fecha'],
            },
        ),
        migrations.CreateModel(
            name='EventoInscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inscripcion', models.DateTimeField(auto_now_add=True)),
                ('asistio', models.BooleanField(default=False)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones_eventos', to='core.alumno')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='core.evento')),
            ],
            options={
                'verbose_name': 'Inscripción a evento',
                'verbose_name_plural': 'Inscripciones a eventos',
                'ordering': ['-fecha_inscripcion'],
                'constraints': [models.UniqueConstraint(fields=('evento', 'alumno'), name='evento_alumno_unico')],
            },
        ),
    ]
