# Generated by Django 6.1.1 on 2026-09-08 16:05

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_maestro_usuario_evento_eventoinscripcion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaMMA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.SlugField(max_length=30, unique=True)),
                ('nombre', models.CharField(max_length=60)),
                ('puntos_maximos', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Categoría MMA',
                'verbose_name_plural': 'Categorías MMA',
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='EvaluacionMMA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('fecha', models.DateField(default=django.utils.timezone.localdate)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('FINALIZADA', 'Finalizada')], default='FINALIZADA', max_length=12)),
                ('notas', models.TextField(blank=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones_mma', to='core.alumno')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluaciones_mma_creadas', to=settings.AUTH_USER_MODEL)),
                ('evaluador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluaciones_mma', to='core.maestro')),
            ],
            options={
                'verbose_name': 'Evaluación MMA',
                'verbose_name_plural': 'Evaluaciones MMA',
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.CreateModel(
            name='HabilidadMMA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('activa', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habilidades', to='core.categoriamma')),
            ],
            options={
                'verbose_name': 'Habilidad MMA',
                'verbose_name_plural': 'Habilidades MMA',
                'ordering': ['categoria__orden', 'orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PuntajeHabilidadMMA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntaje', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puntajes', to='core.evaluacionmma')),
                ('habilidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='puntajes', to='core.habilidadmma')),
            ],
            options={
                'verbose_name': 'Puntaje de habilidad',
                'verbose_name_plural': 'Puntajes de habilidad',
            },
        ),
        migrations.AddIndex(
            model_name='evaluacionmma',
            index=models.Index(fields=['alumno', 'fecha'], name='core_evalua_alumno__057029_idx'),
        ),
        migrations.AddConstraint(
            model_name='evaluacionmma',
            constraint=models.UniqueConstraint(fields=('alumno', 'fecha'), name='evaluacion_mma_unica_por_dia'),
        ),
        migrations.AddConstraint(
            model_name='habilidadmma',
            constraint=models.UniqueConstraint(fields=('categoria', 'nombre'), name='habilidad_mma_unica_por_categoria'),
        ),
        migrations.AddConstraint(
            model_name='puntajehabilidadmma',
            constraint=models.UniqueConstraint(fields=('evaluacion', 'habilidad'), name='puntaje_unico_por_habilidad'),
        ),
    ]
