# Generated by Django 6.1.1 on 2026-09-08 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_catalogo_mma'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experiencia',
            name='defensa',
        ),
        migrations.RemoveField(
            model_name='experiencia',
            name='fecha_ultima_evaluacion',
        ),
        migrations.RemoveField(
            model_name='experiencia',
            name='lucha',
        ),
        migrations.RemoveField(
            model_name='experiencia',
            name='striking',
        ),
    ]
