# Generated by Django 6.1.1 on 2026-09-08 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_quitar_atributos_0_5_experiencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='torneo',
            name='evento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resultados', to='core.evento'),
        ),
        migrations.AddConstraint(
            model_name='torneo',
            constraint=models.UniqueConstraint(condition=models.Q(('evento__isnull', False)), fields=('evento', 'alumno'), name='torneo_resultado_unico_por_evento_alumno'),
        ),
    ]
