# Generated by Django 6.1.1 on 2026-09-08 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_torneo_evento'),
    ]

    operations = [
        migrations.AddField(
            model_name='maestro',
            name='alumnos_asignados',
            field=models.ManyToManyField(blank=True, help_text='Alumnos sueltos que el maestro ve además de los de sus grupos.', related_name='maestros_asignados', to='core.alumno', verbose_name='alumnos asignados individualmente'),
        ),
        migrations.AddField(
            model_name='maestro',
            name='horarios',
            field=models.ManyToManyField(blank=True, help_text='El maestro ve a todos los alumnos activos de estos horarios.', related_name='maestros', to='core.horario', verbose_name='grupos asignados'),
        ),
    ]
