# Generated by Django 6.1.1 on 2026-09-08 22:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_maestro_alcance_grupos_alumnos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='horario',
            name='nombre',
            field=models.CharField(blank=True, help_text="Clase que se da en esta franja, ej. 'Striking' o 'Jiu Jitsu Kids / Striking Kids'.", max_length=80),
        ),
        migrations.AddField(
            model_name='membresia',
            name='descripcion',
            field=models.TextField(blank=True, help_text="Qué incluye el plan, ej. '1 disciplina, horario fijo'."),
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('concepto', models.CharField(help_text="Qué se vendió, ej. 'Inscripción' o 'Guantes 12 oz'.", max_length=120)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodo', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TARJETA', 'Tarjeta'), ('TRANSFERENCIA', 'Transferencia')], default='EFECTIVO', max_length=20)),
                ('fecha', models.DateField(default=django.utils.timezone.localdate)),
                ('nota', models.TextField(blank=True)),
                ('alumno', models.ForeignKey(blank=True, help_text='Opcional: a qué alumno se le vendió. Vacío si fue a un externo.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas', to='core.alumno')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas_registradas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas (otros ingresos)',
                'ordering': ['-fecha', '-id'],
                'indexes': [models.Index(fields=['fecha'], name='core_venta_fecha_a21ebc_idx')],
            },
        ),
    ]
