# Generated by Django 6.1.1 on 2026-09-09 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_venta_horario_nombre_membresia_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='metodo_registro',
            field=models.CharField(choices=[('QR', 'Código QR'), ('MANUAL', 'Manual (recepción)'), ('APP', 'Desde la app del alumno')], default='QR', max_length=10),
        ),
    ]
