# Generated by Django 6.1.1 on 2026-09-23 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_asistencia_metodo_app'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='estatura',
            field=models.PositiveSmallIntegerField(blank=True, help_text='En centímetros', null=True),
        ),
    ]
