# Generated by Django 6.1.1 on 2026-09-23 19:06

from django.db import migrations, models


# Divisiones de peso de MMA (Reglas Unificadas): son las que usa IMMAF para
# amateurs adultos y las que toma la FAMM. Límites oficiales en libras.
DIVISIONES = [
    ("Peso átomo", "Atomweight", "105"),
    ("Peso paja", "Strawweight", "115"),
    ("Peso mosca", "Flyweight", "125"),
    ("Peso gallo", "Bantamweight", "135"),
    ("Peso pluma", "Featherweight", "145"),
    ("Peso ligero", "Lightweight", "155"),
    ("Peso wélter", "Welterweight", "170"),
    ("Peso medio", "Middleweight", "185"),
    ("Peso semipesado", "Light Heavyweight", "205"),
    ("Peso pesado", "Heavyweight", "265"),
    ("Peso superpesado", "Super Heavyweight", None),
]


def cargar_divisiones(apps, schema_editor):
    from decimal import Decimal

    CategoriaPeso = apps.get_model("core", "CategoriaPeso")
    for nombre, nombre_en, limite in DIVISIONES:
        CategoriaPeso.objects.get_or_create(
            nombre=nombre,
            defaults={"nombre_en": nombre_en, "limite_lb": Decimal(limite) if limite else None},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alumno_estatura'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaPeso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej. "Peso pluma"', max_length=40, unique=True)),
                ('nombre_en', models.CharField(blank=True, help_text='Ej. "Featherweight"', max_length=40)),
                ('limite_lb', models.DecimalField(blank=True, decimal_places=1, help_text='Peso máximo de la división en libras. Vacío = sin límite (la más pesada).', max_digits=6, null=True, unique=True)),
                ('organismo', models.CharField(default='IMMAF / FAMM', help_text='Reglamento del que sale el límite.', max_length=60)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Categoría de peso',
                'verbose_name_plural': 'Categorías de peso',
                'ordering': [models.OrderBy(models.F('limite_lb'), nulls_last=True)],
            },
        ),
        migrations.RunPython(cargar_divisiones, migrations.RunPython.noop),
    ]
